enum:

  unidom_product_association:
    complement:
      code: 'CPLM'
    incompatibility:
      code: 'ICPT'
    obsolescence:
      code: 'OBSL'
    substitute:
      code: 'SBST'

  unidom_formset:
    ware:
      code: 'WARE'
    service:
      code: 'SRVC'
    portfolio:
      code: 'PTFL'
